name: animated_item
description: A Flutter plugin that animates ListView and PageView items on scroll, offering diverse effects like scaling, fading, translating, and rotating for dynamic user interactions.
version: 0.0.2
homepage: https://github.com/Conezi/animated_item

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.conezi.animated_item
        pluginClass: AnimatedItemPlugin
      ios:
        pluginClass: AnimatedItemPlugin
      linux:
        pluginClass: AnimatedItemPlugin
      macos:
        pluginClass: AnimatedItemPlugin
      windows:
        pluginClass: AnimatedItemPluginCApi
      web:
        pluginClass: AnimatedItemWeb
        fileName: animated_item_web.dart
